# Numpy -numerical python

In [9]:
!pip install Numpy

In [10]:
import numpy as np

In [ ]:

fungi_species=[3400,2900,3480,8901,1245,9875,1234,8765,7890,15678,12378,4590]

In [21]:
fungi_species

[3400, 2900, 3480, 8901, 1245, 9875, 1234, 8765, 7890, 15678, 12378, 4590]

In [18]:
array

array([ 3400,  2900,  3480,  8901,  1245,  9875,  1234,  8765,  7890,
       15678, 12378,  4590])

In [19]:
print(array)

[ 3400  2900  3480  8901  1245  9875  1234  8765  7890 15678 12378  4590]


In [ ]:

for i in range(len(fungi_species)):
    a=fungi_species[i] * 10
    print(a)


34000
29000
34800
89010
12450
98750
12340
87650
78900
156780
123780
45900


In [ ]:
#time 
import time

start = time.time()

print("\nTime taken for fungi_species:", time.time() - start)



Time taken for fungi_species: 0.0


In [30]:
fungal_occurence=[1.2,4.7,12.0,1.7,1.8,1.0,1.9]
array=np.array(fungal_occurence)
print(array)

[ 1.2  4.7 12.   1.7  1.8  1.   1.9]


In [ ]:
#class
print(type(fungal_occurence))

<class 'list'>


In [ ]:
#shape
array.shape


(7,)

In [ ]:
#dimension
array.ndim

1

In [13]:
# log space # logrithim space array
import numpy as np
fungal_occurence=np.logspace(1,3,3)
fungal_occurence

array([  10.,  100., 1000.])

In [16]:
# number of zeros
fungal_occurence=np.zeros(5)
fungal_occurence

array([0., 0., 0., 0., 0.])

In [ ]:
#convert into array
fungus_infection_rate=[890,567,2345,1234,890,567,235]


In [21]:
arr=np.array(fungus_infection_rate)
arr

array([ 890,  567, 2345, 1234,  890,  567,  235])

In [22]:
#datatype
arr.dtype

dtype('int64')

In [23]:
#shape
arr.shape

(7,)

In [24]:
#size
arr.size

7

In [25]:
#dimension
arr.ndim

1

In [26]:
#operations Arthiematic
fungus_1=np.array([28,34,56,19,10,23,45,13,14,67])



In [27]:
fungus_2=([46,48,25,72,90,67,58,55,80,76])

In [28]:
#add
print(fungus_1+fungus_2)

[ 74  82  81  91 100  90 103  68  94 143]


In [29]:
#subtract
print(fungus_1-fungus_2)

[-18 -14  31 -53 -80 -44 -13 -42 -66  -9]


In [30]:
#multiply
print(fungus_1*fungus_2)

[1288 1632 1400 1368  900 1541 2610  715 1120 5092]


In [31]:
#modulus
print(fungus_1%fungus_2)

[28 34  6 19 10 23 45 13 14 67]


In [32]:
#exponent
print(fungus_1**fungus_2)

[                  0 7710444037034999808                   0
 6408775724441994273                   0 7514925431271492999
 7018070145944232649 4440335197330247461                   0
 1160141020877736433]


In [34]:
#universal functions
arr
#square root
print(np.sqrt(arr))

[29.83286778 23.8117618  48.42520005 35.12833614 29.83286778 23.8117618
 15.32970972]


In [35]:
print(np.sqrt(fungus_1))

[5.29150262 5.83095189 7.48331477 4.35889894 3.16227766 4.79583152
 6.70820393 3.60555128 3.74165739 8.18535277]


In [36]:
print(np.sqrt(fungus_2))

[6.78232998 6.92820323 5.         8.48528137 9.48683298 8.18535277
 7.61577311 7.41619849 8.94427191 8.71779789]


In [37]:
#indexing
print(arr[0])

890


In [41]:
print(fungus_1[3])

19


In [39]:
#negative indexing
print(fungus_2[-2])

80


In [42]:
#slicing
fungus_1

array([28, 34, 56, 19, 10, 23, 45, 13, 14, 67])

In [44]:
print(fungus_1[1:4])

[34 56 19]


In [46]:
print(fungus_1[0:4])

[28 34 56 19]


In [49]:
print(fungus_1[ : :2])

[28 56 10 45 14]


In [52]:
#for multidimensional array
fungus_3=([23,45,67],
          [12,24,70],
          [1,3,8])
arr_1=np.array(fungus_3)
arr_1

array([[23, 45, 67],
       [12, 24, 70],
       [ 1,  3,  8]])

In [55]:
#dimensions
arr_1.ndim

2

In [53]:
#data type
arr_1.dtype

dtype('int64')

In [54]:
#size
arr_1.size

9

In [64]:
#indexing 
print(arr_1[0])

[23 45 67]


In [65]:
print(arr_1[2,1])

3


In [66]:
#slicing of rows,column
print(arr_1[0:2, 1:3])

[[45 67]
 [24 70]]


In [67]:
#single element
print(arr_1[2,2])

8


In [68]:
#operations
#sum
print(sum(arr_1))

[ 36  72 145]


In [70]:
#multiply
print(arr_1*2)


[[ 46  90 134]
 [ 24  48 140]
 [  2   6  16]]


In [71]:
#mean
np.mean(arr_1)

np.float64(28.11111111111111)

In [74]:
#median
np.median(arr_1)

np.float64(23.0)

In [72]:
#max
np.max(arr_1)

np.int64(70)

In [76]:
#min
np.min(arr_1)

np.int64(1)